dist: bionic
language: minimal
before_install:
  # https://github.com/containers/libpod/blob/master/install.md#ubuntu
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common uidmap
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install --install-recommends podman

  # https://clouding.io/kb/en/how-to-install-and-use-podman-on-ubuntu-18-04/
  - ls -1 /etc/containers/registries.conf || true
  - sudo mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io', 'quay.io']" | sudo tee /etc/containers/registries.conf

  - sudo podman pull --quiet ctcoss/fapolicyd
  - mkdir /tmp/allow /tmp/deny
  - cp hello.sh /tmp/deny

before_script:
  - >
    sudo podman run -d -it --name fapolicyd
    --privileged
    --systemd true
    -v /tmp/deny:/deny
    -v /tmp/allow:/allow
    -v $PWD/simple.rules:/etc/fapolicyd/fapolicyd.rules
    ctcoss/fapolicyd

after_script:
  - sudo podman kill fapolicyd

script:
  - sudo podman ps
  - sudo podman logs fapolicyd
  - sudo podman exec -it fapolicyd journalctl -u fapolicyd

  - sudo podman exec -it fapolicyd /deny/hello.sh || true
  - sudo podman exec -it fapolicyd mv /deny/hello.sh /allow
  - sudo podman exec -it fapolicyd /allow/hello.sh

  - sudo podman exec -it fapolicyd journalctl -u fapolicyd
